#!/bin/sh
. /etc/nitro-rc/functions

[ -r /etc/os-release ] && . /etc/os-release
msg "Welcome${NAME:+ to $NAME}!"

# Start core services: one-time system tasks.
for f in /etc/nitro-rc/sysinit.d/*.sh; do
    [ -r "$f" ] && . "$f"
done

msg 'Initialization complete'

[ -x /etc/rc.local ] && /etc/rc.local
